/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import bancodedados.MysqlConnect;
import java.awt.Color;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Franciele Alves Barbosa e Rogério Costa Negro Rocha
 */
public class TelaEsqueceuSenha extends javax.swing.JDialog {

    private Connection conn = null;
    private String minhaMatricula, meuNome;

    /**
     * Creates new form TelaEsqueceuSenha
     */
    public TelaEsqueceuSenha(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            conn = MysqlConnect.connectDB();
            //JOptionPane.showMessageDialog(null, "Conexao bem sucedida");
        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(null, "Erro ao conectar com o Banco de Dados " /*+ ex.getMessage()*/, "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void entraMouse(JButton botao) {
        botao.setOpaque(true);
        botao.setContentAreaFilled(true);
        botao.setBorderPainted(true);
        botao.setBackground(Color.LIGHT_GRAY);
    }

    public void saiMouse(JButton botao) {

        botao.setOpaque(false);
        botao.setContentAreaFilled(false);
        botao.setBorderPainted(false);
    }

    public boolean verificaValidade() {
        minhaMatricula = "\"" + tfMatricula.getText() + "\"";
        meuNome = "\"" + tfNome.getText() + "\"";

        String qry = "SELECT matricula, nome FROM usuarios WHERE matricula= " + minhaMatricula + " AND nome= " + meuNome;

        try (Statement stmt = conn.prepareStatement(qry)) {

            try (ResultSet rs = stmt.executeQuery(qry)) {
                while (rs.next()) {
                    return true;
                }
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }

    public void atualizaSenha() {

        if (!verificaValidade()) {
            JOptionPane.showMessageDialog(this, "Dados inválidos", "ERRO", JOptionPane.ERROR_MESSAGE);
        } else if (!(Arrays.equals(tfSenha.getPassword(), tfConfirmaSenha.getPassword()))) {
            JOptionPane.showMessageDialog(this, "Senhas não coincidem!", "ERRO", JOptionPane.ERROR_MESSAGE);
        } else {
            String qryAtualiza = "UPDATE usuarios SET senha= \"" + String.valueOf(tfSenha.getPassword()) + "\" WHERE matricula= " + minhaMatricula + " AND nome= " + meuNome;

            try (Statement pstmt = conn.createStatement()) {

                int qtd = pstmt.executeUpdate(qryAtualiza);

                if (qtd > 0) {
                    JOptionPane.showMessageDialog(this, "Atualizado!");
                    this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
                } else {
                    JOptionPane.showMessageDialog(this, "Erro!", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException sqle) {
                JOptionPane.showMessageDialog(this, sqle);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEsqueceuSenha = new javax.swing.JPanel();
        lblNomeCompleto = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblConfirmaSenha = new javax.swing.JLabel();
        lblImagemUsuario = new javax.swing.JLabel();
        lblImagemLapis = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfMatricula = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        tfSenha = new javax.swing.JPasswordField();
        tfConfirmaSenha = new javax.swing.JPasswordField();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Esqueceu a Senha");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/Quiron.png")).getImage());

        pnlEsqueceuSenha.setBackground(new java.awt.Color(255, 255, 255));
        pnlEsqueceuSenha.setLayout(null);

        lblNomeCompleto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNomeCompleto.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeCompleto.setText("Nome Completo");
        pnlEsqueceuSenha.add(lblNomeCompleto);
        lblNomeCompleto.setBounds(40, 200, 98, 17);

        lblMatricula.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMatricula.setForeground(new java.awt.Color(255, 255, 255));
        lblMatricula.setText("Nº Matrícula");
        pnlEsqueceuSenha.add(lblMatricula);
        lblMatricula.setBounds(60, 240, 77, 17);

        lblSenha.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("Nova Senha");
        pnlEsqueceuSenha.add(lblSenha);
        lblSenha.setBounds(60, 280, 72, 17);

        lblConfirmaSenha.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblConfirmaSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirmaSenha.setText("Confirme a senha");
        pnlEsqueceuSenha.add(lblConfirmaSenha);
        lblConfirmaSenha.setBounds(20, 320, 110, 17);

        lblImagemUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ícone Usuário M.png"))); // NOI18N
        pnlEsqueceuSenha.add(lblImagemUsuario);
        lblImagemUsuario.setBounds(150, 70, 110, 110);

        lblImagemLapis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ícone Lápis P.png"))); // NOI18N
        pnlEsqueceuSenha.add(lblImagemLapis);
        lblImagemLapis.setBounds(260, 130, 50, 50);

        tfNome.setBackground(new java.awt.Color(153, 153, 153));
        tfNome.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tfNome.setForeground(new java.awt.Color(255, 255, 255));
        pnlEsqueceuSenha.add(tfNome);
        tfNome.setBounds(160, 200, 200, 20);

        tfMatricula.setBackground(new java.awt.Color(153, 153, 153));
        tfMatricula.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tfMatricula.setForeground(new java.awt.Color(255, 255, 255));
        pnlEsqueceuSenha.add(tfMatricula);
        tfMatricula.setBounds(160, 240, 200, 20);

        btnAlterar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        btnAlterar.setBorderPainted(false);
        btnAlterar.setContentAreaFilled(false);
        btnAlterar.setFocusPainted(false);
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlterarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlterarMouseExited(evt);
            }
        });
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        pnlEsqueceuSenha.add(btnAlterar);
        btnAlterar.setBounds(220, 440, 120, 30);

        btnCancelar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlEsqueceuSenha.add(btnCancelar);
        btnCancelar.setBounds(70, 440, 120, 31);

        tfSenha.setBackground(new java.awt.Color(153, 153, 153));
        tfSenha.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tfSenha.setForeground(new java.awt.Color(255, 255, 255));
        pnlEsqueceuSenha.add(tfSenha);
        tfSenha.setBounds(160, 280, 200, 20);

        tfConfirmaSenha.setBackground(new java.awt.Color(153, 153, 153));
        tfConfirmaSenha.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tfConfirmaSenha.setForeground(new java.awt.Color(255, 255, 255));
        pnlEsqueceuSenha.add(tfConfirmaSenha);
        tfConfirmaSenha.setBounds(160, 320, 200, 20);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundo Usuario.png"))); // NOI18N
        pnlEsqueceuSenha.add(lblFundo);
        lblFundo.setBounds(0, 0, 420, 557);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEsqueceuSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEsqueceuSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        this.atualizaSenha();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnAlterarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnAlterar);
    }//GEN-LAST:event_btnAlterarMouseEntered

    private void btnAlterarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnAlterar);
    }//GEN-LAST:event_btnAlterarMouseExited

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnCancelar);
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnCancelar);
    }//GEN-LAST:event_btnCancelarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEsqueceuSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEsqueceuSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEsqueceuSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEsqueceuSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaEsqueceuSenha dialog = new TelaEsqueceuSenha(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblConfirmaSenha;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblImagemLapis;
    private javax.swing.JLabel lblImagemUsuario;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNomeCompleto;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JPanel pnlEsqueceuSenha;
    private javax.swing.JPasswordField tfConfirmaSenha;
    private javax.swing.JTextField tfMatricula;
    private javax.swing.JTextField tfNome;
    private javax.swing.JPasswordField tfSenha;
    // End of variables declaration//GEN-END:variables
}
