/*
 * Classe de Cadastrar Cursos.
 */
package cursos;

import bancodedados.MysqlConnect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Franciele Alves Barbosa e Rogério Costa Negro Rocha
 */
public class TelaCursos extends javax.swing.JFrame {

    Connection conn = null;

    /**
     * Creates new form TelaCursos
     */
    public TelaCursos() {
        initComponents();
        try {
            conn = MysqlConnect.connectDB();
            this.preencheTabela();
        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(null, "Erro ao conectar com o Banco de Dados " /*+ ex.getMessage()*/, "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void entraMouse(JButton botao) {
        botao.setOpaque(true);
        botao.setContentAreaFilled(true);
        botao.setBorderPainted(true);
        botao.setBackground(Color.LIGHT_GRAY);
    }

    public void saiMouse(JButton botao) {
        botao.setOpaque(false);
        botao.setContentAreaFilled(false);
        botao.setBorderPainted(false);
    }

    public void preencheTabela() {
        PreparedStatement pstmt = null;
        ResultSet rs = null;
        DefaultTableModel lista = (DefaultTableModel) tblCursos.getModel();
        lista.setNumRows(0);
        String qry = "SELECT idCursos, curso, nivel FROM cursos order by curso";
        try {
            pstmt = conn.prepareStatement(qry);
            rs = pstmt.executeQuery(qry);

            while (rs.next()) {
                lista.addRow(new String[]{"" + rs.getInt(1), rs.getString("curso"), rs.getString("nivel")});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void liberarCampos() {
        tfCurso.setEnabled(true);
        rbTecnico.setEnabled(true);
        rbSuperior.setEnabled(true);
        rbMestrado.setEnabled(true);
    }

    public void travarCampos() {
        tfCurso.setEnabled(false);
        rbTecnico.setEnabled(false);
        rbSuperior.setEnabled(false);
        rbMestrado.setEnabled(false);
    }

    public void preencherCampos() {
        tfCurso.setText(tblCursos.getValueAt(tblCursos.getSelectedRow(), 1).toString());

        switch (tblCursos.getValueAt(tblCursos.getSelectedRow(), 2).toString()) {
            case "Técnico Integrado":
                rbTecnico.setSelected(true);
                break;
            case "Superior":
                rbSuperior.setSelected(true);
                break;
            case "Mestrado":
                rbMestrado.setSelected(true);
                break;
            default:
                break;
        }
    }

    public void limpaCampos() {
        tfCurso.setText("");
        rbTecnico.setSelected(false);
        rbSuperior.setSelected(false);
        rbMestrado.setSelected(false);
        tblCursos.clearSelection();
    }

    public void resetBotoes() {
        btnCancelar.setVisible(false);
        btnSalvar.setVisible(false);
        btnAdicionar.setVisible(false);

        btnRemover.setVisible(true);
        btnAlterar.setVisible(true);
        btnNovoCurso.setVisible(true);
        tblCursos.setEnabled(true);

        this.travarCampos();
        this.limpaCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgNivel = new javax.swing.ButtonGroup();
        pnlCursos = new javax.swing.JPanel();
        rbTecnico = new javax.swing.JRadioButton();
        lblCurso = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCursos = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnNovoCurso = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        tfCurso = new javax.swing.JTextField();
        rbMestrado = new javax.swing.JRadioButton();
        rbSuperior = new javax.swing.JRadioButton();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciador de Cursos");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        pnlCursos.setLayout(null);

        bgNivel.add(rbTecnico);
        rbTecnico.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rbTecnico.setForeground(new java.awt.Color(255, 255, 255));
        rbTecnico.setText("Técnico Integrado");
        rbTecnico.setContentAreaFilled(false);
        rbTecnico.setFocusPainted(false);
        pnlCursos.add(rbTecnico);
        rbTecnico.setBounds(170, 260, 135, 25);
        rbTecnico.setEnabled(false);

        lblCurso.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblCurso.setForeground(new java.awt.Color(255, 255, 255));
        lblCurso.setText("Curso *");
        pnlCursos.add(lblCurso);
        lblCurso.setBounds(100, 220, 61, 22);

        lblNivel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNivel.setForeground(new java.awt.Color(255, 255, 255));
        lblNivel.setText("Nível *");
        pnlCursos.add(lblNivel);
        lblNivel.setBounds(100, 260, 60, 22);

        tblCursos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblCursos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tblCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Curso", "Nível"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCursosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCursos);
        if (tblCursos.getColumnModel().getColumnCount() > 0) {
            tblCursos.getColumnModel().getColumn(0).setMinWidth(0);
            tblCursos.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblCursos.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        pnlCursos.add(jScrollPane2);
        jScrollPane2.setBounds(90, 80, 470, 130);

        btnAdicionar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionar.setText("Adicionar");
        btnAdicionar.setBorderPainted(false);
        btnAdicionar.setContentAreaFilled(false);
        btnAdicionar.setFocusPainted(false);
        btnAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdicionarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdicionarMouseExited(evt);
            }
        });
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        pnlCursos.add(btnAdicionar);
        btnAdicionar.setBounds(400, 320, 150, 30);
        btnAdicionar.setVisible(false);

        btnRemover.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRemover.setForeground(new java.awt.Color(255, 255, 255));
        btnRemover.setText("Remover");
        btnRemover.setBorderPainted(false);
        btnRemover.setContentAreaFilled(false);
        btnRemover.setFocusPainted(false);
        btnRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRemoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRemoverMouseExited(evt);
            }
        });
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        pnlCursos.add(btnRemover);
        btnRemover.setBounds(100, 360, 150, 30);

        btnAlterar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        btnAlterar.setBorderPainted(false);
        btnAlterar.setContentAreaFilled(false);
        btnAlterar.setFocusPainted(false);
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlterarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlterarMouseExited(evt);
            }
        });
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        pnlCursos.add(btnAlterar);
        btnAlterar.setBounds(250, 360, 150, 30);

        btnNovoCurso.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnNovoCurso.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoCurso.setText("Novo Curso");
        btnNovoCurso.setBorderPainted(false);
        btnNovoCurso.setContentAreaFilled(false);
        btnNovoCurso.setFocusPainted(false);
        btnNovoCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNovoCursoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNovoCursoMouseExited(evt);
            }
        });
        btnNovoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoCursoActionPerformed(evt);
            }
        });
        pnlCursos.add(btnNovoCurso);
        btnNovoCurso.setBounds(400, 360, 150, 30);

        btnSalvar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.setBorderPainted(false);
        btnSalvar.setContentAreaFilled(false);
        btnSalvar.setFocusPainted(false);
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalvarMouseExited(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        pnlCursos.add(btnSalvar);
        btnSalvar.setBounds(250, 320, 150, 30);
        btnSalvar.setVisible(false);

        btnCancelar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlCursos.add(btnCancelar);
        btnCancelar.setBounds(100, 320, 150, 30);
        btnCancelar.setVisible(false);

        tfCurso.setBackground(new java.awt.Color(153, 153, 153));
        tfCurso.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tfCurso.setForeground(new java.awt.Color(255, 255, 255));
        pnlCursos.add(tfCurso);
        tfCurso.setBounds(190, 220, 294, 23);
        tfCurso.setEnabled(false);

        bgNivel.add(rbMestrado);
        rbMestrado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rbMestrado.setForeground(new java.awt.Color(255, 255, 255));
        rbMestrado.setText("Mestrado");
        rbMestrado.setContentAreaFilled(false);
        rbMestrado.setFocusPainted(false);
        pnlCursos.add(rbMestrado);
        rbMestrado.setBounds(420, 260, 82, 25);
        rbMestrado.setEnabled(false);

        bgNivel.add(rbSuperior);
        rbSuperior.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rbSuperior.setForeground(new java.awt.Color(255, 255, 255));
        rbSuperior.setText("Superior");
        rbSuperior.setContentAreaFilled(false);
        rbSuperior.setFocusPainted(false);
        rbSuperior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSuperiorActionPerformed(evt);
            }
        });
        pnlCursos.add(rbSuperior);
        rbSuperior.setBounds(320, 260, 78, 25);
        rbSuperior.setEnabled(false);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundo Pesquisa.png"))); // NOI18N
        pnlCursos.add(lblFundo);
        lblFundo.setBounds(0, 0, 650, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        if(tfCurso.getText().equals("") || !rbTecnico.isSelected() && !rbSuperior.isSelected() && !rbMestrado.isSelected()){
            JOptionPane.showMessageDialog(null, "Preencha os campos obrigatórios", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        else
            this.adicionarCurso();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        PreparedStatement pstmt = null;
        String qry = "UPDATE cursos SET curso= ?, nivel= ? WHERE idCursos= ?";

        try {
            pstmt = conn.prepareStatement(qry);
            pstmt.setString(1, tfCurso.getText());
            if (rbTecnico.isSelected()) {
                pstmt.setString(2, "Técnico Integrado");
            } else if (rbSuperior.isSelected()) {
                pstmt.setString(2, "Superior");
            } else if (rbMestrado.isSelected()) {
                pstmt.setString(2, "Mestrado");
            } else {
                pstmt.setString(2, null);
            }
            pstmt.setString(3, (tblCursos.getValueAt(tblCursos.getSelectedRow(), 0).toString()));

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Atualizado com sucesso!");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar: " + ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        } catch (ArrayIndexOutOfBoundsException ax) {
            JOptionPane.showMessageDialog(null, "Selecione/Insira o curso a ser alterado ", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        this.preencheTabela();
        this.travarCampos();
        this.limpaCampos();
        this.resetBotoes();
    }//GEN-LAST:event_btnSalvarActionPerformed

    public void adicionarCurso() {
        PreparedStatement pstmt = null;
        String qry = "INSERT INTO cursos(curso, nivel) VALUES(?,?)";

        try {
            pstmt = conn.prepareStatement(qry);
            pstmt.setString(1, tfCurso.getText());
            if (rbTecnico.isSelected()) {
                pstmt.setString(2, "Técnico Integrado");
            } else if (rbSuperior.isSelected()) {
                pstmt.setString(2, "Superior");
            } else if (rbMestrado.isSelected()) {
                pstmt.setString(2, "Mestrado");
            } else {
                pstmt.setString(2, null);
            }
            pstmt.executeUpdate();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao inserir: " + ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        this.preencheTabela();
        this.travarCampos();
        this.resetBotoes();
    }
    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        PreparedStatement pstmt = null;
        String qry = "DELETE FROM cursos WHERE idCursos= ?";

        try {
            pstmt = conn.prepareStatement(qry);
            pstmt.setString(1, (tblCursos.getValueAt(tblCursos.getSelectedRow(), 0).toString()));

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Excluido com sucesso!");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir: " + ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        } catch (ArrayIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(null, "Selecione um curso!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        this.preencheTabela();
        this.limpaCampos();
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnNovoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoCursoActionPerformed
        // TODO add your handling code here:
        this.limpaCampos();
        this.liberarCampos();

        btnCancelar.setVisible(true);
        btnSalvar.setVisible(false);
        btnAdicionar.setVisible(true);

        btnRemover.setVisible(false);
        btnAlterar.setVisible(false);
        btnNovoCurso.setVisible(false);

        tblCursos.setEnabled(false);
    }//GEN-LAST:event_btnNovoCursoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.resetBotoes();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        this.liberarCampos();

        btnCancelar.setVisible(true);
        btnSalvar.setVisible(true);
        btnAdicionar.setVisible(false);

        btnRemover.setVisible(false);
        btnAlterar.setVisible(false);
        btnNovoCurso.setVisible(false);

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void tblCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCursosMouseClicked
        // TODO add your handling code here:
        this.preencherCampos();
    }//GEN-LAST:event_tblCursosMouseClicked

    private void rbSuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSuperiorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSuperiorActionPerformed

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnCancelar);
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnCancelar);
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnSalvar);
    }//GEN-LAST:event_btnSalvarMouseEntered

    private void btnSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnSalvar);
    }//GEN-LAST:event_btnSalvarMouseExited

    private void btnAdicionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnAdicionar);
    }//GEN-LAST:event_btnAdicionarMouseEntered

    private void btnAdicionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnAdicionar);
    }//GEN-LAST:event_btnAdicionarMouseExited

    private void btnRemoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoverMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnRemover);
    }//GEN-LAST:event_btnRemoverMouseEntered

    private void btnRemoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoverMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnRemover);
    }//GEN-LAST:event_btnRemoverMouseExited

    private void btnAlterarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnAlterar);
    }//GEN-LAST:event_btnAlterarMouseEntered

    private void btnAlterarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnAlterar);
    }//GEN-LAST:event_btnAlterarMouseExited

    private void btnNovoCursoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoCursoMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnNovoCurso);
    }//GEN-LAST:event_btnNovoCursoMouseEntered

    private void btnNovoCursoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoCursoMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnNovoCurso);
    }//GEN-LAST:event_btnNovoCursoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCursos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgNivel;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnNovoCurso;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JPanel pnlCursos;
    private javax.swing.JRadioButton rbMestrado;
    private javax.swing.JRadioButton rbSuperior;
    private javax.swing.JRadioButton rbTecnico;
    private javax.swing.JTable tblCursos;
    private javax.swing.JTextField tfCurso;
    // End of variables declaration//GEN-END:variables
}
