/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import bancodedados.MysqlConnect;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import principal.TelaPrincipal;

/**
 *
 * @author Franciele Alves Barbosa e Rogério Costa Negro Rocha
 */
public class TelaLogin extends javax.swing.JFrame {

    private Connection conn = null;
    protected String senhaBD;
    public static String cpfBD;
    protected boolean logou = false;
    public static int administradorBD, ativadoBD;

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        try {
            conn = MysqlConnect.connectDB();
            //JOptionPane.showMessageDialog(null, "Conexao bem sucedida");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao conectar com o Banco de Dados " /*+ ex.getMessage()*/, "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogin = new javax.swing.JPanel();
        lblImagemIF = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblEsqueceuSenha = new javax.swing.JLabel();
        tfCpf = new javax.swing.JFormattedTextField();
        tfSenha = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblImagemUsuario = new javax.swing.JLabel();
        lblImagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Login");
        setResizable(false);

        pnlLogin.setLayout(null);

        lblImagemIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logo IF.jpg"))); // NOI18N
        pnlLogin.add(lblImagemIF);
        lblImagemIF.setBounds(0, 0, 175, 60);

        lblCpf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCpf.setForeground(new java.awt.Color(255, 255, 255));
        lblCpf.setText(" CPF");
        pnlLogin.add(lblCpf);
        lblCpf.setBounds(180, 160, 30, 17);

        lblSenha.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("Senha");
        pnlLogin.add(lblSenha);
        lblSenha.setBounds(174, 190, 40, 17);

        lblEsqueceuSenha.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblEsqueceuSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblEsqueceuSenha.setText("Esqueceu sua senha ?");
        lblEsqueceuSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEsqueceuSenhaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEsqueceuSenhaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEsqueceuSenhaMouseExited(evt);
            }
        });
        pnlLogin.add(lblEsqueceuSenha);
        lblEsqueceuSenha.setBounds(220, 260, 140, 17);

        tfCpf.setBackground(new java.awt.Color(153, 153, 153));
        tfCpf.setForeground(new java.awt.Color(255, 255, 255));
        try {
            tfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCpf.setToolTipText("");
        tfCpf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tfCpf.setName(""); // NOI18N
        pnlLogin.add(tfCpf);
        tfCpf.setBounds(220, 160, 140, 23);

        tfSenha.setBackground(new java.awt.Color(153, 153, 153));
        tfSenha.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tfSenha.setForeground(new java.awt.Color(255, 255, 255));
        tfSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfSenhaMouseClicked(evt);
            }
        });
        tfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSenhaKeyPressed(evt);
            }
        });
        pnlLogin.add(tfSenha);
        tfSenha.setBounds(220, 190, 140, 23);

        btnLogin.setBackground(new java.awt.Color(0, 153, 51));
        btnLogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlLogin.add(btnLogin);
        btnLogin.setBounds(220, 230, 140, 25);

        lblImagemUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ícone Usuário M.png"))); // NOI18N
        pnlLogin.add(lblImagemUsuario);
        lblImagemUsuario.setBounds(230, 20, 110, 110);

        lblImagemFundo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundo Login.png"))); // NOI18N
        pnlLogin.add(lblImagemFundo);
        lblImagemFundo.setBounds(0, 0, 530, 290);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSenhaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnLogin.doClick();
        }
    }//GEN-LAST:event_tfSenhaKeyPressed

    private void tfSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSenhaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSenhaMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String qryLogin = "Select cpf, senha, administrador, ativado FROM usuarios";

        try (Statement stmt = conn.createStatement()) {
            try (ResultSet rs = stmt.executeQuery(qryLogin)) {
                while (rs.next()) {
                    cpfBD = rs.getString("cpf");
                    senhaBD = rs.getString("senha");
                    administradorBD = rs.getInt("administrador");
                    ativadoBD = rs.getInt("ativado");

                    if ((tfCpf.getText().equals(cpfBD)) && (String.valueOf(tfSenha.getPassword()).equals(senhaBD))) {
                        if (ativadoBD == 0) {
                            break;
                        } else {
                            logou = true;
                            TelaPrincipal telaPrincipal = new TelaPrincipal();
                            telaPrincipal.setVisible(true);
                            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
                            break;
                        }
                    }
                }
                if (logou == false) {
                    if (ativadoBD == 0) {
                        JOptionPane.showMessageDialog(null, "Usuário Inativo", "ERRO", JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "Login inválido!", "ERRO", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    public int getAdministradorBD() {
        return administradorBD;
    }

    private void lblEsqueceuSenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEsqueceuSenhaMouseEntered
        // TODO add your handling code here:
        lblEsqueceuSenha.setForeground(Color.red);
    }//GEN-LAST:event_lblEsqueceuSenhaMouseEntered

    private void lblEsqueceuSenhaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEsqueceuSenhaMouseExited
        // TODO add your handling code here:
        lblEsqueceuSenha.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblEsqueceuSenhaMouseExited

    private void lblEsqueceuSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEsqueceuSenhaMouseClicked
        // TODO add your handling code here:
        TelaEsqueceuSenha esqueceuSenha = new TelaEsqueceuSenha(this, true);
        esqueceuSenha.setVisible(true);
    }//GEN-LAST:event_lblEsqueceuSenhaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEsqueceuSenha;
    private javax.swing.JLabel lblImagemFundo;
    private javax.swing.JLabel lblImagemIF;
    private javax.swing.JLabel lblImagemUsuario;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JFormattedTextField tfCpf;
    private javax.swing.JPasswordField tfSenha;
    // End of variables declaration//GEN-END:variables
}
