/*
 * Classe do Relatório.
 */
package relatorio;

import bancodedados.MysqlConnect;
import fichaatendimento.FichasAtendimento;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Franciele Alves Barbosa e Rogério Costa Negro Rocha
 */
public class TelaRelatorios extends javax.swing.JFrame {

    Connection conn;

    /**
     * Creates new form TelaRelatorios
     */
    public TelaRelatorios() {
        initComponents();
        try {
            conn = MysqlConnect.connectDB();
        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(null, "Erro ao conectar com o Banco de Dados " /*+ ex.getMessage()*/, "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void entraMouse(JButton botao) {
        botao.setOpaque(true);
        botao.setContentAreaFilled(true);
        botao.setBorderPainted(true);
        botao.setBackground(Color.LIGHT_GRAY);
    }

    public void saiMouse(JButton botao) {
        botao.setOpaque(false);
        botao.setContentAreaFilled(false);
        botao.setBorderPainted(false);
    }

    public static String getDatString(String dataDMA) {
        String reportDate = "";
        // Converte a data no formato dd/MM/yyyy
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        DateFormat dfDMA = new SimpleDateFormat("dd/MM/yyyy");
        java.util.Date enteredDate;
        try {
            enteredDate = dfDMA.parse(dataDMA);
            reportDate = df.format(enteredDate);
        } catch (ParseException ex) {
            Logger.getLogger(FichasAtendimento.class.getName()).log(Level.SEVERE, null, ex);
        }
        //String reportDate = df.format(enteredDate);
        return reportDate;
    }

    public static String getDatDate(String dataDMA) {
        String reportDate = "";
        // Converte a data no formato yyyy-MM-dd
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        DateFormat dfDMA = new SimpleDateFormat("dd/MM/yyyy");
        java.util.Date enteredDate;
        try {
            enteredDate = df.parse(dataDMA);
            reportDate = dfDMA.format(enteredDate);
            reportDate.replace('-', '/');
        } catch (ParseException ex) {
            Logger.getLogger(FichasAtendimento.class.getName()).log(Level.SEVERE, null, ex);
        }
        //String reportDate = df.format(enteredDate);
        return reportDate;
    }
    
    public void calculaEncaminhamentos(){
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        String qry = "SELECT COUNT(idEncaminhamentos) FROM encaminhamentosHospital WHERE data >= ? AND data <= ?";

        try {
            pstmt = conn.prepareStatement(qry);
            pstmt.setString(1, this.getDatString(tfDtInicial.getText()));
            pstmt.setString(2, this.getDatString(tfDtFinal.getText()));

            rs = pstmt.executeQuery();

            while (rs.next()) {
                tfEncaminhamentos.setText(rs.getString("COUNT(idEncaminhamentos)"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void calculaAtendimentos() {
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        String qry = "SELECT COUNT(idFichas) FROM fichas WHERE data >= ? AND data <= ?";

        try {
            pstmt = conn.prepareStatement(qry);
            pstmt.setString(1, this.getDatString(tfDtInicial.getText()));
            pstmt.setString(2, this.getDatString(tfDtFinal.getText()));

            rs = pstmt.executeQuery();

            while (rs.next()) {
                tfConsultas.setText(rs.getString("COUNT(idFichas)"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRelatorio = new javax.swing.JPanel();
        btnConsultar = new javax.swing.JButton();
        btnPdf = new javax.swing.JButton();
        lblDtInicial = new javax.swing.JLabel();
        lblDtFinal = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        tfConsultas = new javax.swing.JTextField();
        tfDtInicial = new javax.swing.JFormattedTextField();
        tfDtFinal = new javax.swing.JFormattedTextField();
        lblLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfEncaminhamentos = new javax.swing.JTextField();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatórios");
        setResizable(false);

        pnlRelatorio.setLayout(null);

        btnConsultar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("CONSULTAR");
        btnConsultar.setBorderPainted(false);
        btnConsultar.setContentAreaFilled(false);
        btnConsultar.setFocusPainted(false);
        btnConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsultarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConsultarMouseExited(evt);
            }
        });
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        pnlRelatorio.add(btnConsultar);
        btnConsultar.setBounds(200, 220, 150, 30);

        btnPdf.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPdf.setForeground(new java.awt.Color(255, 255, 255));
        btnPdf.setText("GERAR PDF");
        btnPdf.setBorderPainted(false);
        btnPdf.setContentAreaFilled(false);
        btnPdf.setFocusPainted(false);
        btnPdf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPdfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPdfMouseExited(evt);
            }
        });
        pnlRelatorio.add(btnPdf);
        btnPdf.setBounds(0, 220, 150, 30);
        btnPdf.setVisible(false);

        lblDtInicial.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDtInicial.setForeground(new java.awt.Color(255, 255, 255));
        lblDtInicial.setText("DATA INICIAL");
        pnlRelatorio.add(lblDtInicial);
        lblDtInicial.setBounds(50, 80, 100, 20);

        lblDtFinal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDtFinal.setForeground(new java.awt.Color(255, 255, 255));
        lblDtFinal.setText("DATA FINAL");
        pnlRelatorio.add(lblDtFinal);
        lblDtFinal.setBounds(300, 80, 90, 20);

        lblNumero.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(255, 255, 255));
        lblNumero.setText("NÚMERO DE CONSULTAS REALIZADAS");
        pnlRelatorio.add(lblNumero);
        lblNumero.setBounds(70, 130, 270, 17);

        tfConsultas.setEditable(false);
        tfConsultas.setBackground(new java.awt.Color(153, 153, 153));
        tfConsultas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tfConsultas.setForeground(new java.awt.Color(255, 255, 255));
        pnlRelatorio.add(tfConsultas);
        tfConsultas.setBounds(370, 130, 90, 20);

        tfDtInicial.setBackground(new java.awt.Color(153, 153, 153));
        tfDtInicial.setForeground(new java.awt.Color(255, 255, 255));
        try {
            tfDtInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDtInicial.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pnlRelatorio.add(tfDtInicial);
        tfDtInicial.setBounds(170, 80, 90, 28);

        tfDtFinal.setBackground(new java.awt.Color(153, 153, 153));
        tfDtFinal.setForeground(new java.awt.Color(255, 255, 255));
        try {
            tfDtFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDtFinal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pnlRelatorio.add(tfDtFinal);
        tfDtFinal.setBounds(400, 80, 80, 28);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logo IF.jpg"))); // NOI18N
        pnlRelatorio.add(lblLogo);
        lblLogo.setBounds(200, 0, 170, 60);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NÚMERO DE ENCAMINHAMENTOS AO HOSPITAL");
        pnlRelatorio.add(jLabel1);
        jLabel1.setBounds(14, 170, 340, 17);

        tfEncaminhamentos.setEditable(false);
        tfEncaminhamentos.setBackground(new java.awt.Color(153, 153, 153));
        tfEncaminhamentos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tfEncaminhamentos.setForeground(new java.awt.Color(255, 255, 255));
        pnlRelatorio.add(tfEncaminhamentos);
        tfEncaminhamentos.setBounds(370, 170, 90, 20);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundo Login.png"))); // NOI18N
        pnlRelatorio.add(lblFundo);
        lblFundo.setBounds(0, 0, 540, 290);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnConsultar);
    }//GEN-LAST:event_btnConsultarMouseEntered

    private void btnConsultarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnConsultar);
    }//GEN-LAST:event_btnConsultarMouseExited

    private void btnPdfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPdfMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnPdf);
    }//GEN-LAST:event_btnPdfMouseEntered

    private void btnPdfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPdfMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnPdf);
    }//GEN-LAST:event_btnPdfMouseExited

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        if(tfDtInicial.getText().replace("/", "").trim().length()==0 || tfDtFinal.getText().replace("/", "").trim().length()==0){
            JOptionPane.showMessageDialog(null, "Preencha a data inicial e a final", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        else{
            this.calculaAtendimentos();
            this.calculaEncaminhamentos();
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRelatorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnPdf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDtFinal;
    private javax.swing.JLabel lblDtInicial;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JPanel pnlRelatorio;
    private javax.swing.JTextField tfConsultas;
    private javax.swing.JFormattedTextField tfDtFinal;
    private javax.swing.JFormattedTextField tfDtInicial;
    private javax.swing.JTextField tfEncaminhamentos;
    // End of variables declaration//GEN-END:variables
}
