/*
 * Tela Principal (Inical), onde possui todas as ações do sistema.
 */
//Tamanho desejado [1370, 710]
//pnl [1000, 550]
package principal;

import bancodedados.MysqlConnect;
import cursos.pnlGerenciarCursos;
import gerenciarpacientes.pnlCadastroPaciente;
import gerenciarusuarios.pnlAlterarUsuario;
import gerenciarusuarios.pnlAtivarUsuario;
import gerenciarusuarios.pnlCadastrarUsuarios;
import hospital.pnlEncaminhamentoHospital;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import login.TelaLogin;
import relatorio.pnlRelatorios;

/**
 *
 * @author Franciele Alves Barbosa e Rogério Costa Negro Rocha
 */
public final class TelaPrincipal extends javax.swing.JFrame {

    Connection conn = null;
    public int administradorBD;
    public static int controlePesquisa = 0;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        try {
            conn = MysqlConnect.connectDB();
            this.verificaAdministrador();
            this.voltarHome();
            lblNomeUsuario.setText(TelaLogin.nomeUsuario);
        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(null, "Erro ao conectar com o Banco de Dados " /*+ ex.getMessage()*/, "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void verificaAdministrador() {
        if (TelaLogin.administradorBD != 1) {
            btnAdicionarUsuario.setEnabled(false);
            btnAtivarUsuario.setEnabled(false);
            btnGerenciarCursos.setEnabled(false);
            //lblImagemCursos.setEnabled(false);
            lblGerenciaCursos.setEnabled(false);
        }
    }

    public void entraMouse(JButton botao) {
        botao.setOpaque(true);
        botao.setContentAreaFilled(true);
        botao.setBorderPainted(true);
        botao.setBackground(Color.LIGHT_GRAY);
    }

    public void saiMouse(JButton botao) {

        botao.setOpaque(false);
        botao.setContentAreaFilled(false);
        botao.setBorderPainted(false);
    }

    public void fechaFrame() {
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }

    public static void abrirJPainel(JPanel meuPainel) {
        meuPainel.setSize(1000, 550);
        //meuPainel.setLocation(5,5);
        pnlTelaAtual.removeAll();
        pnlTelaAtual.add(meuPainel, BorderLayout.CENTER);
        pnlTelaAtual.revalidate();
        pnlTelaAtual.repaint();
        pnlTelaAtual.setVisible(true);
    }

    public static void voltarHome() {
        pnlTelaAtual.setVisible(false);
        lblTextoAtual.setText("Bem Vindo(a)");
        pnlInicial pnlInicial = new pnlInicial();
        abrirJPainel(pnlInicial);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlPrincipal = new javax.swing.JPanel();
        lblTextoAtual = new javax.swing.JLabel();
        pnlMenuVertical = new javax.swing.JPanel();
        lblLogoQuiron = new javax.swing.JLabel();
        lblTextoQuiron = new javax.swing.JLabel();
        sSeparador1 = new javax.swing.JSeparator();
        lblAtendimento = new javax.swing.JLabel();
        btnFichas = new javax.swing.JButton();
        btnEncaminhamentos = new javax.swing.JButton();
        sSeparador2 = new javax.swing.JSeparator();
        btnAdicionarPaciente = new javax.swing.JButton();
        sSeparador3 = new javax.swing.JSeparator();
        lblCartaoVacina = new javax.swing.JLabel();
        btnEditarCartao = new javax.swing.JButton();
        sSeparador4 = new javax.swing.JSeparator();
        lblRelatorios = new javax.swing.JLabel();
        btnRelatorio = new javax.swing.JButton();
        sSeparador5 = new javax.swing.JSeparator();
        lblGerenciaUsuarios = new javax.swing.JLabel();
        btnAdicionarUsuario = new javax.swing.JButton();
        btnAlterarUsuario = new javax.swing.JButton();
        btnAtivarUsuario = new javax.swing.JButton();
        sSeparador6 = new javax.swing.JSeparator();
        lblGerenciaCursos = new javax.swing.JLabel();
        btnGerenciarCursos = new javax.swing.JButton();
        lblGerenciarPacientes = new javax.swing.JLabel();
        lblImagemAtendimento = new javax.swing.JLabel();
        lblImagemPacientes = new javax.swing.JLabel();
        btnAdcionarServidor = new javax.swing.JButton();
        btnAlterarPaciente = new javax.swing.JButton();
        lblImagemRelatorios = new javax.swing.JLabel();
        lblImagemCartaoVacina = new javax.swing.JLabel();
        lblImagemGerenciaUsuarios = new javax.swing.JLabel();
        lblImagemCursos = new javax.swing.JLabel();
        lblFundoVertical = new javax.swing.JLabel();
        pnlMenuHorizontal = new javax.swing.JPanel();
        lblNomeUsuario = new javax.swing.JLabel();
        lblLogoIf = new javax.swing.JLabel();
        lblFundoHorizontal = new javax.swing.JLabel();
        pnlTelaAtual = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Tela Principal");
        setExtendedState(MAXIMIZED_BOTH);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/Quiron.png")).getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextoAtual.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblTextoAtual.setForeground(new java.awt.Color(96, 173, 224));
        pnlPrincipal.add(lblTextoAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 80, 1010, 60));

        pnlMenuVertical.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenuVertical.setForeground(new java.awt.Color(102, 102, 102));
        pnlMenuVertical.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogoQuiron.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogoQuiron.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Quiron P.png"))); // NOI18N
        pnlMenuVertical.add(lblLogoQuiron, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 12, 294, -1));

        lblTextoQuiron.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTextoQuiron.setForeground(new java.awt.Color(102, 102, 102));
        lblTextoQuiron.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoQuiron.setText("QUÍRON");
        pnlMenuVertical.add(lblTextoQuiron, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 119, 294, -1));

        sSeparador1.setForeground(new java.awt.Color(102, 102, 102));
        pnlMenuVertical.add(sSeparador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 147, 290, 10));

        lblAtendimento.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblAtendimento.setForeground(new java.awt.Color(96, 173, 224));
        lblAtendimento.setText("Atendimento");
        pnlMenuVertical.add(lblAtendimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 163, 169, -1));

        btnFichas.setBackground(new java.awt.Color(102, 102, 102));
        btnFichas.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnFichas.setForeground(new java.awt.Color(51, 51, 51));
        btnFichas.setText("Fichas                  ");
        btnFichas.setBorderPainted(false);
        btnFichas.setContentAreaFilled(false);
        btnFichas.setFocusable(false);
        btnFichas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFichas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFichasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFichasMouseExited(evt);
            }
        });
        btnFichas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFichasActionPerformed(evt);
            }
        });
        pnlMenuVertical.add(btnFichas, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 191, -1, 30));

        btnEncaminhamentos.setBackground(new java.awt.Color(102, 102, 102));
        btnEncaminhamentos.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnEncaminhamentos.setForeground(new java.awt.Color(51, 51, 51));
        btnEncaminhamentos.setText("Encamin. ao Hospital");
        btnEncaminhamentos.setBorderPainted(false);
        btnEncaminhamentos.setContentAreaFilled(false);
        btnEncaminhamentos.setFocusable(false);
        btnEncaminhamentos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEncaminhamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEncaminhamentosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEncaminhamentosMouseExited(evt);
            }
        });
        btnEncaminhamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncaminhamentosActionPerformed(evt);
            }
        });
        pnlMenuVertical.add(btnEncaminhamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 227, -1, 30));

        sSeparador2.setForeground(new java.awt.Color(102, 102, 102));
        pnlMenuVertical.add(sSeparador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 267, 290, 10));

        btnAdicionarPaciente.setBackground(new java.awt.Color(102, 102, 102));
        btnAdicionarPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnAdicionarPaciente.setForeground(new java.awt.Color(51, 51, 51));
        btnAdicionarPaciente.setText("Adicionar Paciente");
        btnAdicionarPaciente.setBorderPainted(false);
        btnAdicionarPaciente.setContentAreaFilled(false);
        btnAdicionarPaciente.setFocusPainted(false);
        btnAdicionarPaciente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdicionarPaciente.setPreferredSize(new java.awt.Dimension(255, 109));
        btnAdicionarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdicionarPacienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdicionarPacienteMouseExited(evt);
            }
        });
        btnAdicionarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarPacienteActionPerformed(evt);
            }
        });
        pnlMenuVertical.add(btnAdicionarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 311, 188, 30));

        sSeparador3.setForeground(new java.awt.Color(102, 102, 102));
        pnlMenuVertical.add(sSeparador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 423, 290, 10));

        lblCartaoVacina.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblCartaoVacina.setForeground(new java.awt.Color(96, 173, 224));
        lblCartaoVacina.setText("Cartão de Vacinação");
        pnlMenuVertical.add(lblCartaoVacina, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 439, 188, 20));

        btnEditarCartao.setBackground(new java.awt.Color(102, 102, 102));
        btnEditarCartao.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnEditarCartao.setForeground(new java.awt.Color(51, 51, 51));
        btnEditarCartao.setText("Gerenciar Cartões     ");
        btnEditarCartao.setBorderPainted(false);
        btnEditarCartao.setContentAreaFilled(false);
        btnEditarCartao.setFocusPainted(false);
        btnEditarCartao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEditarCartao.setPreferredSize(new java.awt.Dimension(255, 109));
        btnEditarCartao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarCartaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarCartaoMouseExited(evt);
            }
        });
        btnEditarCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCartaoActionPerformed(evt);
            }
        });
        pnlMenuVertical.add(btnEditarCartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 465, 190, 30));

        sSeparador4.setForeground(new java.awt.Color(102, 102, 102));
        pnlMenuVertical.add(sSeparador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 535, 290, 10));

        lblRelatorios.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblRelatorios.setForeground(new java.awt.Color(96, 173, 224));
        lblRelatorios.setText("Relatórios");
        pnlMenuVertical.add(lblRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 551, 188, -1));

        btnRelatorio.setBackground(new java.awt.Color(102, 102, 102));
        btnRelatorio.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnRelatorio.setForeground(new java.awt.Color(51, 51, 51));
        btnRelatorio.setText("Gerar Relatório     ");
        btnRelatorio.setBorderPainted(false);
        btnRelatorio.setContentAreaFilled(false);
        btnRelatorio.setFocusPainted(false);
        btnRelatorio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRelatorio.setPreferredSize(new java.awt.Dimension(255, 109));
        btnRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRelatorioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRelatorioMouseExited(evt);
            }
        });
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });
        pnlMenuVertical.add(btnRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 579, 188, 30));

        sSeparador5.setForeground(new java.awt.Color(102, 102, 102));
        pnlMenuVertical.add(sSeparador5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 659, 290, 10));

        lblGerenciaUsuarios.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblGerenciaUsuarios.setForeground(new java.awt.Color(96, 173, 224));
        lblGerenciaUsuarios.setText("Gerenciar Usuarios");
        pnlMenuVertical.add(lblGerenciaUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 675, 188, -1));

        btnAdicionarUsuario.setBackground(new java.awt.Color(102, 102, 102));
        btnAdicionarUsuario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnAdicionarUsuario.setForeground(new java.awt.Color(51, 51, 51));
        btnAdicionarUsuario.setText("Adicionar Usuario");
        btnAdicionarUsuario.setBorderPainted(false);
        btnAdicionarUsuario.setContentAreaFilled(false);
        btnAdicionarUsuario.setFocusPainted(false);
        btnAdicionarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdicionarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdicionarUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdicionarUsuarioMouseExited(evt);
            }
        });
        btnAdicionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarUsuarioActionPerformed(evt);
            }
        });
        pnlMenuVertical.add(btnAdicionarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 703, 188, -1));

        btnAlterarUsuario.setBackground(new java.awt.Color(102, 102, 102));
        btnAlterarUsuario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnAlterarUsuario.setForeground(new java.awt.Color(51, 51, 51));
        btnAlterarUsuario.setText("Alterar                ");
        btnAlterarUsuario.setBorderPainted(false);
        btnAlterarUsuario.setContentAreaFilled(false);
        btnAlterarUsuario.setFocusable(false);
        btnAlterarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAlterarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlterarUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlterarUsuarioMouseExited(evt);
            }
        });
        btnAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarUsuarioActionPerformed(evt);
            }
        });
        pnlMenuVertical.add(btnAlterarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 739, 188, 30));

        btnAtivarUsuario.setBackground(new java.awt.Color(102, 102, 102));
        btnAtivarUsuario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnAtivarUsuario.setForeground(new java.awt.Color(51, 51, 51));
        btnAtivarUsuario.setText("Ativar/Inativar");
        btnAtivarUsuario.setBorderPainted(false);
        btnAtivarUsuario.setContentAreaFilled(false);
        btnAtivarUsuario.setFocusPainted(false);
        btnAtivarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAtivarUsuario.setPreferredSize(new java.awt.Dimension(255, 109));
        btnAtivarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAtivarUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAtivarUsuarioMouseExited(evt);
            }
        });
        btnAtivarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtivarUsuarioActionPerformed(evt);
            }
        });
        pnlMenuVertical.add(btnAtivarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 775, 188, 30));

        sSeparador6.setForeground(new java.awt.Color(102, 102, 102));
        pnlMenuVertical.add(sSeparador6, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 811, 290, 10));

        lblGerenciaCursos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblGerenciaCursos.setForeground(new java.awt.Color(96, 173, 224));
        lblGerenciaCursos.setText("Cursos");
        pnlMenuVertical.add(lblGerenciaCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 827, 188, -1));

        btnGerenciarCursos.setBackground(new java.awt.Color(102, 102, 102));
        btnGerenciarCursos.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnGerenciarCursos.setForeground(new java.awt.Color(51, 51, 51));
        btnGerenciarCursos.setText("Gerenciar Cursos");
        btnGerenciarCursos.setBorderPainted(false);
        btnGerenciarCursos.setContentAreaFilled(false);
        btnGerenciarCursos.setFocusPainted(false);
        btnGerenciarCursos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGerenciarCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGerenciarCursosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGerenciarCursosMouseExited(evt);
            }
        });
        btnGerenciarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarCursosActionPerformed(evt);
            }
        });
        pnlMenuVertical.add(btnGerenciarCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 855, 188, -1));

        lblGerenciarPacientes.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblGerenciarPacientes.setForeground(new java.awt.Color(96, 173, 224));
        lblGerenciarPacientes.setText("Gerenciar Pacientes");
        pnlMenuVertical.add(lblGerenciarPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 283, 188, -1));

        lblImagemAtendimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ícone Médico P.png"))); // NOI18N
        pnlMenuVertical.add(lblImagemAtendimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 163, -1, -1));

        lblImagemPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ícone Enfermeira P.png"))); // NOI18N
        pnlMenuVertical.add(lblImagemPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 283, -1, 134));

        btnAdcionarServidor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnAdcionarServidor.setForeground(new java.awt.Color(51, 51, 51));
        btnAdcionarServidor.setText("Adicionar Servidor");
        btnAdcionarServidor.setBorderPainted(false);
        btnAdcionarServidor.setContentAreaFilled(false);
        btnAdcionarServidor.setFocusPainted(false);
        btnAdcionarServidor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdcionarServidor.setPreferredSize(new java.awt.Dimension(255, 109));
        btnAdcionarServidor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdcionarServidorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdcionarServidorMouseExited(evt);
            }
        });
        btnAdcionarServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdcionarServidorActionPerformed(evt);
            }
        });
        pnlMenuVertical.add(btnAdcionarServidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 347, 190, 30));

        btnAlterarPaciente.setBackground(new java.awt.Color(102, 102, 102));
        btnAlterarPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnAlterarPaciente.setForeground(new java.awt.Color(51, 51, 51));
        btnAlterarPaciente.setText("Pesquisar");
        btnAlterarPaciente.setBorderPainted(false);
        btnAlterarPaciente.setContentAreaFilled(false);
        btnAlterarPaciente.setFocusPainted(false);
        btnAlterarPaciente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAlterarPaciente.setPreferredSize(new java.awt.Dimension(255, 109));
        btnAlterarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarPacienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlterarPacienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlterarPacienteMouseExited(evt);
            }
        });
        btnAlterarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarPacienteActionPerformed(evt);
            }
        });
        pnlMenuVertical.add(btnAlterarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 383, 190, 30));

        lblImagemRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ícone Relatório Médico P.png"))); // NOI18N
        pnlMenuVertical.add(lblImagemRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 551, -1, -1));

        lblImagemCartaoVacina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ícone Exames P.png"))); // NOI18N
        lblImagemCartaoVacina.setMaximumSize(new java.awt.Dimension(100, 98));
        lblImagemCartaoVacina.setMinimumSize(new java.awt.Dimension(100, 98));
        pnlMenuVertical.add(lblImagemCartaoVacina, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 439, -1, -1));

        lblImagemGerenciaUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ícone Usuário P Azul.png"))); // NOI18N
        pnlMenuVertical.add(lblImagemGerenciaUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 675, -1, 130));

        lblImagemCursos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblImagemCursos.setForeground(new java.awt.Color(255, 255, 255));
        lblImagemCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ícone Relatório P.png"))); // NOI18N
        pnlMenuVertical.add(lblImagemCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 827, -1, -1));

        lblFundoVertical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Low Poly branco recortado.jpg"))); // NOI18N
        pnlMenuVertical.add(lblFundoVertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 940));

        pnlPrincipal.add(pnlMenuVertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlMenuHorizontal.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenuHorizontal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNomeUsuario.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNomeUsuario.setForeground(new java.awt.Color(102, 102, 102));
        lblNomeUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNomeUsuario.setText("Usuário");
        pnlMenuHorizontal.add(lblNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 21, 300, -1));

        lblLogoIf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Icone IF P.png"))); // NOI18N
        pnlMenuHorizontal.add(lblLogoIf, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 11, -1, -1));

        lblFundoHorizontal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Low Poly branco horizontal.jpg"))); // NOI18N
        pnlMenuHorizontal.add(lblFundoHorizontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, -1));

        pnlPrincipal.add(pnlMenuHorizontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 0, 1050, -1));

        pnlTelaAtual.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlTelaAtualLayout = new javax.swing.GroupLayout(pnlTelaAtual);
        pnlTelaAtual.setLayout(pnlTelaAtualLayout);
        pnlTelaAtualLayout.setHorizontalGroup(
            pnlTelaAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        pnlTelaAtualLayout.setVerticalGroup(
            pnlTelaAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        pnlPrincipal.add(pnlTelaAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 146, -1, -1));
        pnlTelaAtual.setVisible(false);

        jScrollPane1.setViewportView(pnlPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1338, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarUsuarioMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnAdicionarUsuario);
    }//GEN-LAST:event_btnAdicionarUsuarioMouseEntered

    private void btnAdicionarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarUsuarioMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnAdicionarUsuario);
    }//GEN-LAST:event_btnAdicionarUsuarioMouseExited

    private void btnAdicionarPacienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarPacienteMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnAdicionarPaciente);
    }//GEN-LAST:event_btnAdicionarPacienteMouseEntered

    private void btnAdicionarPacienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarPacienteMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnAdicionarPaciente);
    }//GEN-LAST:event_btnAdicionarPacienteMouseExited

    private void btnEditarCartaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarCartaoMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnEditarCartao);
    }//GEN-LAST:event_btnEditarCartaoMouseEntered

    private void btnEditarCartaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarCartaoMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnEditarCartao);
    }//GEN-LAST:event_btnEditarCartaoMouseExited

    private void btnRelatorioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatorioMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnRelatorio);
    }//GEN-LAST:event_btnRelatorioMouseEntered

    private void btnRelatorioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatorioMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnRelatorio);
    }//GEN-LAST:event_btnRelatorioMouseExited

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        // TODO add your handling code here:
        lblTextoAtual.setText("Gerar Relatórios");
        pnlRelatorios pnlRelatorios = new pnlRelatorios();
        TelaPrincipal.abrirJPainel(pnlRelatorios);
        //TelaRelatorios relatorios = new TelaRelatorios();
        //relatorios.setVisible(true);
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void btnAlterarPacienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarPacienteMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnAlterarPaciente);
    }//GEN-LAST:event_btnAlterarPacienteMouseEntered

    private void btnAlterarPacienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarPacienteMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnAlterarPaciente);
    }//GEN-LAST:event_btnAlterarPacienteMouseExited

    private void btnAtivarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtivarUsuarioMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnAtivarUsuario);
    }//GEN-LAST:event_btnAtivarUsuarioMouseEntered

    private void btnAtivarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtivarUsuarioMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnAtivarUsuario);
    }//GEN-LAST:event_btnAtivarUsuarioMouseExited

    private void btnAtivarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtivarUsuarioActionPerformed
        // TODO add your handling code here:
        lblTextoAtual.setText("Ativar / Inativar Usuarios");
        pnlAtivarUsuario pnlAtivarUsuario = new pnlAtivarUsuario();
        TelaPrincipal.abrirJPainel(pnlAtivarUsuario);
        //TelaAtivarUsuario alteraRemoveUsuario = new TelaAtivarUsuario();
        //alteraRemoveUsuario.setVisible(true);
    }//GEN-LAST:event_btnAtivarUsuarioActionPerformed

    private void btnAdicionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarUsuarioActionPerformed
        // TODO add your handling code here:
        lblTextoAtual.setText("Cadastrar Usuário");
        pnlCadastrarUsuarios pnlCadastrarUsuario = new pnlCadastrarUsuarios();
        TelaPrincipal.abrirJPainel(pnlCadastrarUsuario);
        //TelaCadastroUsuario cadastroUsuario = new TelaCadastroUsuario();
        //cadastroUsuario.setVisible(true);
    }//GEN-LAST:event_btnAdicionarUsuarioActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:       
        int op = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "ATENÇÃO", JOptionPane.YES_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarUsuarioActionPerformed
        // TODO add your handling code here:
        lblTextoAtual.setText("Alterar Usuários");
        pnlAlterarUsuario pnlAlterarUsuario = new pnlAlterarUsuario();
        TelaPrincipal.abrirJPainel(pnlAlterarUsuario);
        //TelaAlteraUsuario alteraUsuario = new TelaAlteraUsuario();
        //alteraUsuario.setVisible(true);
    }//GEN-LAST:event_btnAlterarUsuarioActionPerformed

    private void btnAlterarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarUsuarioMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnAlterarUsuario);
    }//GEN-LAST:event_btnAlterarUsuarioMouseEntered

    private void btnAlterarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarUsuarioMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnAlterarUsuario);
    }//GEN-LAST:event_btnAlterarUsuarioMouseExited

    private void btnFichasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFichasMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnFichas);
    }//GEN-LAST:event_btnFichasMouseEntered

    private void btnFichasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFichasMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnFichas);
    }//GEN-LAST:event_btnFichasMouseExited

    private void btnFichasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFichasActionPerformed
        // TODO add your handling code here:
        TelaPrincipal.controlePesquisa = 1;
        PesquisaPaciente pesquisaPaciente = new PesquisaPaciente(this, true);
        pesquisaPaciente.setVisible(true);
    }//GEN-LAST:event_btnFichasActionPerformed

    private void btnAdicionarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarPacienteActionPerformed
        // TODO add your handling code here:
        //TelaCadastroPaciente cadastroPacientes = new TelaCadastroPaciente(); 
        lblTextoAtual.setText("Cadastrar Paciente");
        pnlCadastroPaciente cadastroPaciente = new pnlCadastroPaciente();
        TelaPrincipal.abrirJPainel(cadastroPaciente);
    }//GEN-LAST:event_btnAdicionarPacienteActionPerformed

    private void btnGerenciarCursosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGerenciarCursosMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnGerenciarCursos);
    }//GEN-LAST:event_btnGerenciarCursosMouseEntered

    private void btnGerenciarCursosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGerenciarCursosMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnGerenciarCursos);
    }//GEN-LAST:event_btnGerenciarCursosMouseExited

    private void btnGerenciarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarCursosActionPerformed
        // TODO add your handling code here:
        lblTextoAtual.setText("Gerenciar Cursos");
        pnlGerenciarCursos pnlCursos = new pnlGerenciarCursos();
        TelaPrincipal.abrirJPainel(pnlCursos);
        //TelaCursos cursos = new TelaCursos();
        //cursos.setVisible(true);
    }//GEN-LAST:event_btnGerenciarCursosActionPerformed

    private void btnAlterarPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarPacienteMouseClicked
        // TODO add your handling code here:  
    }//GEN-LAST:event_btnAlterarPacienteMouseClicked

    private void btnAlterarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarPacienteActionPerformed
        // TODO add your handling code here:
        TelaPrincipal.controlePesquisa = 0;
        PesquisaPaciente pesquisa = new PesquisaPaciente(this, true);
        pesquisa.setVisible(true);
    }//GEN-LAST:event_btnAlterarPacienteActionPerformed

    private void btnEditarCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCartaoActionPerformed
        // TODO add your handling code here:
        TelaPrincipal.controlePesquisa = 3;
        PesquisaPaciente pesquisa = new PesquisaPaciente(this, true);
        pesquisa.setVisible(true);
    }//GEN-LAST:event_btnEditarCartaoActionPerformed

    private void btnEncaminhamentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncaminhamentosMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnEncaminhamentos);
    }//GEN-LAST:event_btnEncaminhamentosMouseEntered

    private void btnEncaminhamentosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncaminhamentosMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnEncaminhamentos);
    }//GEN-LAST:event_btnEncaminhamentosMouseExited

    private void btnEncaminhamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncaminhamentosActionPerformed
        // TODO add your handling code here:
        lblTextoAtual.setText("Encaminhamentos ao Hospital");
        pnlEncaminhamentoHospital pnlEncaminhamentoHospital = new pnlEncaminhamentoHospital();
        TelaPrincipal.abrirJPainel(pnlEncaminhamentoHospital);
        //TelaEncaminhamentos encaminhamentos = new TelaEncaminhamentos();
        //encaminhamentos.setVisible(true);
    }//GEN-LAST:event_btnEncaminhamentosActionPerformed

    private void btnAdcionarServidorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdcionarServidorMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnAdcionarServidor);
    }//GEN-LAST:event_btnAdcionarServidorMouseEntered

    private void btnAdcionarServidorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdcionarServidorMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnAdcionarServidor);
    }//GEN-LAST:event_btnAdcionarServidorMouseExited

    private void btnAdcionarServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdcionarServidorActionPerformed
        // TODO add your handling code here:
        //TelaAtivarUsuario alteraRemoveUsuario = new TelaAtivarUsuario();
        //alteraRemoveUsuario.setVisible(true);
    }//GEN-LAST:event_btnAdcionarServidorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdcionarServidor;
    private javax.swing.JButton btnAdicionarPaciente;
    private javax.swing.JButton btnAdicionarUsuario;
    private javax.swing.JButton btnAlterarPaciente;
    private javax.swing.JButton btnAlterarUsuario;
    private javax.swing.JButton btnAtivarUsuario;
    private javax.swing.JButton btnEditarCartao;
    private javax.swing.JButton btnEncaminhamentos;
    private javax.swing.JButton btnFichas;
    private javax.swing.JButton btnGerenciarCursos;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAtendimento;
    private javax.swing.JLabel lblCartaoVacina;
    private javax.swing.JLabel lblFundoHorizontal;
    private javax.swing.JLabel lblFundoVertical;
    private javax.swing.JLabel lblGerenciaCursos;
    private javax.swing.JLabel lblGerenciaUsuarios;
    private javax.swing.JLabel lblGerenciarPacientes;
    private javax.swing.JLabel lblImagemAtendimento;
    private javax.swing.JLabel lblImagemCartaoVacina;
    private javax.swing.JLabel lblImagemCursos;
    private javax.swing.JLabel lblImagemGerenciaUsuarios;
    private javax.swing.JLabel lblImagemPacientes;
    private javax.swing.JLabel lblImagemRelatorios;
    private javax.swing.JLabel lblLogoIf;
    private javax.swing.JLabel lblLogoQuiron;
    private javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JLabel lblRelatorios;
    public static javax.swing.JLabel lblTextoAtual;
    private javax.swing.JLabel lblTextoQuiron;
    private javax.swing.JPanel pnlMenuHorizontal;
    private javax.swing.JPanel pnlMenuVertical;
    private javax.swing.JPanel pnlPrincipal;
    public static javax.swing.JPanel pnlTelaAtual;
    private javax.swing.JSeparator sSeparador1;
    private javax.swing.JSeparator sSeparador2;
    private javax.swing.JSeparator sSeparador3;
    private javax.swing.JSeparator sSeparador4;
    private javax.swing.JSeparator sSeparador5;
    private javax.swing.JSeparator sSeparador6;
    // End of variables declaration//GEN-END:variables

}
