/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciarusuarios;

import bancodedados.MysqlConnect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Franciele Alves Barbosa e Rogério Costa Negro Rocha
 */
public class TelaAtivarUsuario extends javax.swing.JFrame {

    Connection conn = null;
    public String numMatricula;

    /**
     * Creates new form TelaAlteraeRomovUser
     */
    public TelaAtivarUsuario() {
        initComponents();
        try {
            conn = MysqlConnect.connectDB();
            this.caixaUsuario();
        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(null, "Erro ao conectar com o Banco de Dados " /*+ ex.getMessage()*/, "ERRO", JOptionPane.ERROR_MESSAGE);
        }

    }

    public void entraMouse(JButton botao) {
        botao.setOpaque(true);
        botao.setContentAreaFilled(true);
        botao.setBorderPainted(true);
        botao.setBackground(Color.LIGHT_GRAY);
    }

    public void saiMouse(JButton botao) {

        botao.setOpaque(false);
        botao.setContentAreaFilled(false);
        botao.setBorderPainted(false);
    }

    public void caixaUsuario() {
        jcbUsuarios.removeAllItems();
        String qryNome = "SELECT * FROM usuarios";

        try (Statement stmt = conn.prepareStatement(qryNome)) {
            try (ResultSet rs = stmt.executeQuery(qryNome)) {

                while (rs.next()) {
                    jcbUsuarios.addItem(rs.getString("matricula"));
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void usuarioSelecionado() {
        PreparedStatement pstmt = null;
        ResultSet rs = null;
        numMatricula = (String) jcbUsuarios.getSelectedItem();
        String qry = "SELECT * FROM usuarios WHERE matricula= ?";

        try {
            pstmt = conn.prepareStatement(qry);
            pstmt.setString(1, numMatricula);
            rs = pstmt.executeQuery();

            while (rs.next()) {
                tfUsuarioSelecionado.setText(rs.getString("nome"));
                if (rs.getString("ativado").equals("1")) {
                    tfStatus.setText("Ativado");
                } else {
                    tfStatus.setText("Inativado");
                }
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAtivarUsuario = new javax.swing.JPanel();
        jcbUsuarios = new javax.swing.JComboBox<>();
        btnInativar = new javax.swing.JButton();
        lblImagemUsuario = new javax.swing.JLabel();
        lblImagemLapis = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JLabel();
        lblUsuarioSelecionado = new javax.swing.JLabel();
        btnAtivar = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        tfUsuarioSelecionado = new javax.swing.JTextField();
        tfStatus = new javax.swing.JTextField();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ativar/Desativar Usuarios");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        pnlAtivarUsuario.setBackground(new java.awt.Color(255, 255, 255));
        pnlAtivarUsuario.setLayout(null);

        jcbUsuarios.setBackground(new java.awt.Color(153, 153, 153));
        jcbUsuarios.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcbUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        jcbUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbUsuariosActionPerformed(evt);
            }
        });
        pnlAtivarUsuario.add(jcbUsuarios);
        jcbUsuarios.setBounds(170, 200, 144, 23);

        btnInativar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnInativar.setForeground(new java.awt.Color(255, 255, 255));
        btnInativar.setText("Inativar");
        btnInativar.setBorderPainted(false);
        btnInativar.setContentAreaFilled(false);
        btnInativar.setFocusPainted(false);
        btnInativar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInativarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInativarMouseExited(evt);
            }
        });
        btnInativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInativarActionPerformed(evt);
            }
        });
        pnlAtivarUsuario.add(btnInativar);
        btnInativar.setBounds(70, 380, 120, 36);

        lblImagemUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ícone Usuário M.png"))); // NOI18N
        pnlAtivarUsuario.add(lblImagemUsuario);
        lblImagemUsuario.setBounds(150, 70, 110, 110);

        lblImagemLapis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ícone Lápis P.png"))); // NOI18N
        pnlAtivarUsuario.add(lblImagemLapis);
        lblImagemLapis.setBounds(260, 120, 60, 50);

        lblMatricula.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMatricula.setForeground(new java.awt.Color(255, 255, 255));
        lblMatricula.setText("Selecione a matricula");
        pnlAtivarUsuario.add(lblMatricula);
        lblMatricula.setBounds(20, 200, 132, 17);

        lblUsuarioSelecionado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblUsuarioSelecionado.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarioSelecionado.setText("Usuário Selecionado");
        pnlAtivarUsuario.add(lblUsuarioSelecionado);
        lblUsuarioSelecionado.setBounds(30, 240, 123, 17);

        btnAtivar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnAtivar.setForeground(new java.awt.Color(255, 255, 255));
        btnAtivar.setText("Ativar");
        btnAtivar.setBorderPainted(false);
        btnAtivar.setContentAreaFilled(false);
        btnAtivar.setFocusPainted(false);
        btnAtivar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAtivarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAtivarMouseExited(evt);
            }
        });
        btnAtivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtivarActionPerformed(evt);
            }
        });
        pnlAtivarUsuario.add(btnAtivar);
        btnAtivar.setBounds(250, 380, 120, 31);

        lblStatus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblStatus.setText("Status");
        pnlAtivarUsuario.add(lblStatus);
        lblStatus.setBounds(120, 280, 39, 17);

        tfUsuarioSelecionado.setEditable(false);
        tfUsuarioSelecionado.setBackground(new java.awt.Color(153, 153, 153));
        tfUsuarioSelecionado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tfUsuarioSelecionado.setForeground(new java.awt.Color(255, 255, 255));
        pnlAtivarUsuario.add(tfUsuarioSelecionado);
        tfUsuarioSelecionado.setBounds(170, 240, 230, 20);

        tfStatus.setEditable(false);
        tfStatus.setBackground(new java.awt.Color(153, 153, 153));
        tfStatus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tfStatus.setForeground(new java.awt.Color(255, 255, 255));
        pnlAtivarUsuario.add(tfStatus);
        tfStatus.setBounds(170, 280, 230, 23);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundo Usuario.png"))); // NOI18N
        pnlAtivarUsuario.add(lblFundo);
        lblFundo.setBounds(0, 0, 420, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAtivarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAtivarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbUsuariosActionPerformed
        // TODO add your handling code here:
        this.usuarioSelecionado();
    }//GEN-LAST:event_jcbUsuariosActionPerformed

    private void btnInativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInativarActionPerformed
        // TODO add your handling code here:
        numMatricula = (String) jcbUsuarios.getSelectedItem();
        if (jcbUsuarios.getItemCount() <= 1) {
            JOptionPane.showMessageDialog(this, "Só há um usuário registrado");
        } else {
            int op = JOptionPane.showConfirmDialog(null, "Deseja realmente inativar?", "ATENÇÃO", JOptionPane.YES_OPTION);
            if (op == JOptionPane.YES_OPTION) {

                PreparedStatement pstmt = null;
                //String qry = "DELETE FROM usuarios WHERE matricula= ?";
                String qry = "UPDATE usuarios SET ativado= ? WHERE matricula= ?";

                try {
                    pstmt = conn.prepareStatement(qry);
                    pstmt.setInt(1, 0);
                    pstmt.setString(2, numMatricula);
                    pstmt.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Inativado com sucesso!");
                    this.caixaUsuario();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Erro ao inativar: " + ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnInativarActionPerformed

    private void btnAtivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtivarActionPerformed
        // TODO add your handling code here:
        PreparedStatement pstmt = null;
        //String qry = "DELETE FROM usuarios WHERE matricula= ?";
        String qry = "UPDATE usuarios SET ativado= ? WHERE matricula= ?";

        try {
            pstmt = conn.prepareStatement(qry);
            pstmt.setInt(1, 1);
            pstmt.setString(2, numMatricula);
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Ativado com sucesso!");
            this.caixaUsuario();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao ativar: " + ex);
        }
    }//GEN-LAST:event_btnAtivarActionPerformed

    private void btnAtivarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtivarMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnAtivar);
    }//GEN-LAST:event_btnAtivarMouseEntered

    private void btnAtivarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtivarMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnAtivar);
    }//GEN-LAST:event_btnAtivarMouseExited

    private void btnInativarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInativarMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnInativar);
    }//GEN-LAST:event_btnInativarMouseEntered

    private void btnInativarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInativarMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnInativar);
    }//GEN-LAST:event_btnInativarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtivarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtivarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtivarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtivarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtivarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtivar;
    private javax.swing.JButton btnInativar;
    private javax.swing.JComboBox<String> jcbUsuarios;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblImagemLapis;
    private javax.swing.JLabel lblImagemUsuario;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUsuarioSelecionado;
    private javax.swing.JPanel pnlAtivarUsuario;
    private javax.swing.JTextField tfStatus;
    private javax.swing.JTextField tfUsuarioSelecionado;
    // End of variables declaration//GEN-END:variables
}
