/*
 * Classe de Cadastrar Usuário.
 */
package gerenciarusuarios;

import bancodedados.MysqlConnect;
import java.awt.Color;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Franciele Alves Barbosa e Rogério Costa Negro Rocha
 */
public class TelaCadastroUsuario extends javax.swing.JFrame {

    private Connection conn = null;
    protected String nome, matricula, cpf, telefone;
    protected String senha, confirmaSenha;

    /**
     * Creates new form TelaCadastroUsuario
     */
    public TelaCadastroUsuario() {
        initComponents();

        try {
            conn = MysqlConnect.connectDB();
            //JOptionPane.showMessageDialog(null, "Conexao bem sucedida");
        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(null, "Erro ao conectar com o Banco de Dados " /*+ ex.getMessage()*/, "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void entraMouse(JButton botao) {
        botao.setOpaque(true);
        botao.setContentAreaFilled(true);
        botao.setBorderPainted(true);
        botao.setBackground(Color.LIGHT_GRAY);
    }

    public void saiMouse(JButton botao) {
        botao.setOpaque(false);
        botao.setContentAreaFilled(false);
        botao.setBorderPainted(false);
    }
    
    public void cadastrarUsuario(){
        nome = tfNome.getText();
        matricula = tfMatricula.getText();
        cpf = tfCpf.getText();
        telefone = tfTelefone.getText();
        if (!(Arrays.equals(tfSenha.getPassword(), tfConfirmaSenha.getPassword()))) {
            JOptionPane.showMessageDialog(null, "Senhas não coincidem!", "ERRO", JOptionPane.ERROR_MESSAGE);
        } else {
            String qryStr = "INSERT INTO usuarios(matricula, nome, cpf, telefone, senha, administrador, ativado)" + "VALUES (?,?,?,?,?,?, ?)";

            try (PreparedStatement pstmt = conn.prepareStatement(qryStr)) {
                pstmt.setString(1, matricula);
                pstmt.setString(2, nome);
                pstmt.setString(3, cpf);
                pstmt.setString(4, telefone);
                pstmt.setString(5, String.valueOf(tfSenha.getPassword()));
                if (rbAdministrador.isSelected()) {
                    pstmt.setInt(6, 1);
                } else {
                    pstmt.setInt(6, 0);
                }
                pstmt.setInt(7, 1);

                int qtd = pstmt.executeUpdate();

                if (qtd > 0) {
                    JOptionPane.showMessageDialog(this, "Registrado!");
                    this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao Registrar", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro: Matrícula já registrada", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgUsuario = new javax.swing.ButtonGroup();
        pnlNovoUsuario = new javax.swing.JPanel();
        lblImagemUsuario = new javax.swing.JLabel();
        lblImagemMais = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblConfirmaSenha = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfMatricula = new javax.swing.JTextField();
        tfTelefone = new javax.swing.JTextField();
        tfSenha = new javax.swing.JPasswordField();
        tfConfirmaSenha = new javax.swing.JPasswordField();
        tfCpf = new javax.swing.JFormattedTextField();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        rbAdministrador = new javax.swing.JRadioButton();
        rbPadrao = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Usuário");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlNovoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        pnlNovoUsuario.setLayout(null);

        lblImagemUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ícone Usuário M.png"))); // NOI18N
        pnlNovoUsuario.add(lblImagemUsuario);
        lblImagemUsuario.setBounds(150, 70, 110, 110);

        lblImagemMais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ícone + P.png"))); // NOI18N
        pnlNovoUsuario.add(lblImagemMais);
        lblImagemMais.setBounds(260, 130, 50, 50);

        lblNome.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Nome Completo *");
        pnlNovoUsuario.add(lblNome);
        lblNome.setBounds(20, 200, 109, 17);

        lblMatricula.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMatricula.setForeground(new java.awt.Color(255, 255, 255));
        lblMatricula.setText("Nº Matrícula *");
        pnlNovoUsuario.add(lblMatricula);
        lblMatricula.setBounds(40, 240, 88, 17);

        lblCpf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCpf.setForeground(new java.awt.Color(255, 255, 255));
        lblCpf.setText("CPF *");
        pnlNovoUsuario.add(lblCpf);
        lblCpf.setBounds(90, 280, 37, 17);

        lblTelefone.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefone.setText("Telefone");
        pnlNovoUsuario.add(lblTelefone);
        lblTelefone.setBounds(73, 320, 60, 17);

        lblSenha.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("Senha");
        pnlNovoUsuario.add(lblSenha);
        lblSenha.setBounds(90, 360, 38, 17);

        lblConfirmaSenha.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblConfirmaSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirmaSenha.setText("Confirme a senha");
        pnlNovoUsuario.add(lblConfirmaSenha);
        lblConfirmaSenha.setBounds(20, 400, 110, 17);

        tfNome.setBackground(new java.awt.Color(153, 153, 153));
        tfNome.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tfNome.setForeground(new java.awt.Color(255, 255, 255));
        tfNome.setCaretColor(new java.awt.Color(255, 255, 255));
        pnlNovoUsuario.add(tfNome);
        tfNome.setBounds(140, 200, 250, 23);

        tfMatricula.setBackground(new java.awt.Color(153, 153, 153));
        tfMatricula.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tfMatricula.setForeground(new java.awt.Color(255, 255, 255));
        tfMatricula.setCaretColor(new java.awt.Color(255, 255, 255));
        pnlNovoUsuario.add(tfMatricula);
        tfMatricula.setBounds(140, 240, 250, 23);

        tfTelefone.setBackground(new java.awt.Color(153, 153, 153));
        tfTelefone.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tfTelefone.setForeground(new java.awt.Color(255, 255, 255));
        tfTelefone.setCaretColor(new java.awt.Color(255, 255, 255));
        pnlNovoUsuario.add(tfTelefone);
        tfTelefone.setBounds(140, 320, 250, 23);

        tfSenha.setBackground(new java.awt.Color(153, 153, 153));
        tfSenha.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tfSenha.setForeground(new java.awt.Color(255, 255, 255));
        tfSenha.setCaretColor(new java.awt.Color(255, 255, 255));
        pnlNovoUsuario.add(tfSenha);
        tfSenha.setBounds(140, 360, 250, 23);

        tfConfirmaSenha.setBackground(new java.awt.Color(153, 153, 153));
        tfConfirmaSenha.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tfConfirmaSenha.setForeground(new java.awt.Color(255, 255, 255));
        tfConfirmaSenha.setCaretColor(new java.awt.Color(255, 255, 255));
        tfConfirmaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfConfirmaSenhaActionPerformed(evt);
            }
        });
        pnlNovoUsuario.add(tfConfirmaSenha);
        tfConfirmaSenha.setBounds(140, 400, 250, 23);

        tfCpf.setBackground(new java.awt.Color(153, 153, 153));
        tfCpf.setForeground(new java.awt.Color(255, 255, 255));
        try {
            tfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCpf.setCaretColor(new java.awt.Color(255, 255, 255));
        tfCpf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pnlNovoUsuario.add(tfCpf);
        tfCpf.setBounds(140, 280, 250, 23);

        btnCadastrar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setBorderPainted(false);
        btnCadastrar.setContentAreaFilled(false);
        btnCadastrar.setFocusPainted(false);
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseExited(evt);
            }
        });
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        pnlNovoUsuario.add(btnCadastrar);
        btnCadastrar.setBounds(233, 500, 140, 30);

        btnCancelar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlNovoUsuario.add(btnCancelar);
        btnCancelar.setBounds(57, 500, 130, 30);

        rbAdministrador.setBackground(new java.awt.Color(255, 255, 255));
        bgUsuario.add(rbAdministrador);
        rbAdministrador.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rbAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        rbAdministrador.setText("Administrador");
        rbAdministrador.setContentAreaFilled(false);
        rbAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rbAdministrador.setFocusPainted(false);
        pnlNovoUsuario.add(rbAdministrador);
        rbAdministrador.setBounds(140, 440, 130, 25);

        rbPadrao.setBackground(new java.awt.Color(255, 255, 255));
        bgUsuario.add(rbPadrao);
        rbPadrao.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rbPadrao.setForeground(new java.awt.Color(255, 255, 255));
        rbPadrao.setSelected(true);
        rbPadrao.setText("Padrão");
        rbPadrao.setContentAreaFilled(false);
        rbPadrao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rbPadrao.setFocusPainted(false);
        rbPadrao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPadraoActionPerformed(evt);
            }
        });
        pnlNovoUsuario.add(rbPadrao);
        rbPadrao.setBounds(260, 440, 90, 25);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuário");
        pnlNovoUsuario.add(jLabel1);
        jLabel1.setBounds(80, 440, 47, 17);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundo Usuario.png"))); // NOI18N
        pnlNovoUsuario.add(lblFundo);
        lblFundo.setBounds(0, 0, 420, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNovoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNovoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        String cpfVazio= tfCpf.getText();
        cpfVazio= cpfVazio.replace("/", "");
        cpfVazio= cpfVazio.replace(".", "");
        cpfVazio= cpfVazio.replace("-", "");
        if(tfNome.getText().equals("") || tfMatricula.getText().equals("") || cpfVazio.trim().length()==0){
            JOptionPane.showMessageDialog(null, "Preencha os campos obrigatórios (campos com *)", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        else
            this.cadastrarUsuario();        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tfConfirmaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfConfirmaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfConfirmaSenhaActionPerformed

    private void rbPadraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPadraoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPadraoActionPerformed

    private void btnCadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnCadastrar);
    }//GEN-LAST:event_btnCadastrarMouseEntered

    private void btnCadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnCadastrar);
    }//GEN-LAST:event_btnCadastrarMouseExited

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnCancelar);
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnCancelar);
    }//GEN-LAST:event_btnCancelarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgUsuario;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblConfirmaSenha;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblImagemMais;
    private javax.swing.JLabel lblImagemUsuario;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JPanel pnlNovoUsuario;
    private javax.swing.JRadioButton rbAdministrador;
    private javax.swing.JRadioButton rbPadrao;
    private javax.swing.JPasswordField tfConfirmaSenha;
    private javax.swing.JFormattedTextField tfCpf;
    private javax.swing.JTextField tfMatricula;
    private javax.swing.JTextField tfNome;
    private javax.swing.JPasswordField tfSenha;
    private javax.swing.JTextField tfTelefone;
    // End of variables declaration//GEN-END:variables
}
