/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import bancodedados.MysqlConnect;
import cursos.TelaCursos;
import gerenciarpacientes.TelaCadastroPaciente;
import gerenciarusuarios.TelaAlteraUsuario;
import gerenciarusuarios.TelaCadastroUsuario;
import gerenciarusuarios.TelaAtivarUsuario;
import hospital.TelaEncaminhamentos;
import java.awt.Color;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import login.TelaLogin;
import relatorio.TelaRelatorios;

/**
 *
 * @author Franciele Alves Barbosa e Rogério Costa Negro Rocha
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Connection conn = null;
    public int administradorBD;
    public static int controlePesquisa = 0;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        try {
            conn = MysqlConnect.connectDB();
            this.verificaAdministrador();
            //JOptionPane.showMessageDialog(null, "Conexao bem sucedida");
        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(null, "Erro ao conectar com o Banco de Dados " /*+ ex.getMessage()*/, "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void verificaAdministrador() {
        if (TelaLogin.administradorBD != 1) {
            btnAdicionarUsuario.setEnabled(false);
            btnAtivarUsuario.setEnabled(false);
            btnGerenciarCursos.setEnabled(false);
            lblImagemCursos.setEnabled(false);
            lblGerenciaCursos.setEnabled(false);
        }
    }

    public void entraMouse(JButton botao) {
        botao.setOpaque(true);
        botao.setContentAreaFilled(true);
        botao.setBorderPainted(true);
        botao.setBackground(Color.LIGHT_GRAY);
    }

    public void saiMouse(JButton botao) {

        botao.setOpaque(false);
        botao.setContentAreaFilled(false);
        botao.setBorderPainted(false);
    }

    public void fechaFrame() {
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        btnAdicionarUsuario = new javax.swing.JButton();
        btnAtivarUsuario = new javax.swing.JButton();
        btnAdicionarPaciente = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        btnEditarCartao = new javax.swing.JButton();
        btnAlterarPaciente = new javax.swing.JButton();
        btnAlterarUsuario = new javax.swing.JButton();
        btnFichas = new javax.swing.JButton();
        btnEncaminhamentos = new javax.swing.JButton();
        btnGerenciarCursos = new javax.swing.JButton();
        lblAtendimento = new javax.swing.JLabel();
        lblGerenciaCursos = new javax.swing.JLabel();
        lblGerenciarPacientes = new javax.swing.JLabel();
        lblImagemAtendimento = new javax.swing.JLabel();
        lblImagemPacientes = new javax.swing.JLabel();
        lblImagemGerenciaUsuarios = new javax.swing.JLabel();
        lblCartaoVacina = new javax.swing.JLabel();
        lblGerenciaUsuarios = new javax.swing.JLabel();
        lblRelatorios = new javax.swing.JLabel();
        lblImagemRelatorios = new javax.swing.JLabel();
        lblImagemCursos = new javax.swing.JLabel();
        lblImagemCartaoVacina = new javax.swing.JLabel();
        lblImagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Tela Principal");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlPrincipal.setLayout(null);

        btnAdicionarUsuario.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAdicionarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionarUsuario.setText("Adicionar Usuario");
        btnAdicionarUsuario.setBorderPainted(false);
        btnAdicionarUsuario.setContentAreaFilled(false);
        btnAdicionarUsuario.setFocusPainted(false);
        btnAdicionarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdicionarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdicionarUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdicionarUsuarioMouseExited(evt);
            }
        });
        btnAdicionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarUsuarioActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnAdicionarUsuario);
        btnAdicionarUsuario.setBounds(580, 290, 150, 30);

        btnAtivarUsuario.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAtivarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnAtivarUsuario.setText("Ativar/Inativar");
        btnAtivarUsuario.setBorderPainted(false);
        btnAtivarUsuario.setContentAreaFilled(false);
        btnAtivarUsuario.setFocusPainted(false);
        btnAtivarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAtivarUsuario.setPreferredSize(new java.awt.Dimension(255, 109));
        btnAtivarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAtivarUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAtivarUsuarioMouseExited(evt);
            }
        });
        btnAtivarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtivarUsuarioActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnAtivarUsuario);
        btnAtivarUsuario.setBounds(580, 350, 150, 30);

        btnAdicionarPaciente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAdicionarPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionarPaciente.setText("Adicionar Paciente");
        btnAdicionarPaciente.setBorderPainted(false);
        btnAdicionarPaciente.setContentAreaFilled(false);
        btnAdicionarPaciente.setFocusPainted(false);
        btnAdicionarPaciente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdicionarPaciente.setPreferredSize(new java.awt.Dimension(255, 109));
        btnAdicionarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdicionarPacienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdicionarPacienteMouseExited(evt);
            }
        });
        btnAdicionarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarPacienteActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnAdicionarPaciente);
        btnAdicionarPaciente.setBounds(240, 290, 150, 30);

        btnRelatorio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        btnRelatorio.setText("Gerar Relatório     ");
        btnRelatorio.setBorderPainted(false);
        btnRelatorio.setContentAreaFilled(false);
        btnRelatorio.setFocusPainted(false);
        btnRelatorio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRelatorio.setPreferredSize(new java.awt.Dimension(255, 109));
        btnRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRelatorioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRelatorioMouseExited(evt);
            }
        });
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnRelatorio);
        btnRelatorio.setBounds(580, 160, 160, 30);

        btnEditarCartao.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnEditarCartao.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarCartao.setText("Gerenciar Cartões     ");
        btnEditarCartao.setBorderPainted(false);
        btnEditarCartao.setContentAreaFilled(false);
        btnEditarCartao.setFocusPainted(false);
        btnEditarCartao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEditarCartao.setPreferredSize(new java.awt.Dimension(255, 109));
        btnEditarCartao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarCartaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarCartaoMouseExited(evt);
            }
        });
        btnEditarCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCartaoActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnEditarCartao);
        btnEditarCartao.setBounds(230, 450, 170, 30);

        btnAlterarPaciente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAlterarPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarPaciente.setText("Pesquisar");
        btnAlterarPaciente.setBorderPainted(false);
        btnAlterarPaciente.setContentAreaFilled(false);
        btnAlterarPaciente.setFocusPainted(false);
        btnAlterarPaciente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAlterarPaciente.setPreferredSize(new java.awt.Dimension(255, 109));
        btnAlterarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarPacienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlterarPacienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlterarPacienteMouseExited(evt);
            }
        });
        btnAlterarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarPacienteActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnAlterarPaciente);
        btnAlterarPaciente.setBounds(240, 320, 150, 30);

        btnAlterarUsuario.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAlterarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarUsuario.setText("Alterar                ");
        btnAlterarUsuario.setBorderPainted(false);
        btnAlterarUsuario.setContentAreaFilled(false);
        btnAlterarUsuario.setFocusable(false);
        btnAlterarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAlterarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlterarUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlterarUsuarioMouseExited(evt);
            }
        });
        btnAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarUsuarioActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnAlterarUsuario);
        btnAlterarUsuario.setBounds(580, 320, 150, 30);

        btnFichas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnFichas.setForeground(new java.awt.Color(255, 255, 255));
        btnFichas.setText("Fichas                  ");
        btnFichas.setBorderPainted(false);
        btnFichas.setContentAreaFilled(false);
        btnFichas.setFocusable(false);
        btnFichas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFichas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFichasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFichasMouseExited(evt);
            }
        });
        btnFichas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFichasActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnFichas);
        btnFichas.setBounds(240, 160, 150, 30);

        btnEncaminhamentos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnEncaminhamentos.setForeground(new java.awt.Color(255, 255, 255));
        btnEncaminhamentos.setText("Encaminhamentos ao Hospital");
        btnEncaminhamentos.setBorderPainted(false);
        btnEncaminhamentos.setContentAreaFilled(false);
        btnEncaminhamentos.setFocusable(false);
        btnEncaminhamentos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEncaminhamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEncaminhamentosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEncaminhamentosMouseExited(evt);
            }
        });
        btnEncaminhamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncaminhamentosActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnEncaminhamentos);
        btnEncaminhamentos.setBounds(240, 190, 220, 30);

        btnGerenciarCursos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnGerenciarCursos.setForeground(new java.awt.Color(255, 255, 255));
        btnGerenciarCursos.setText("Gerenciar Cursos");
        btnGerenciarCursos.setBorderPainted(false);
        btnGerenciarCursos.setContentAreaFilled(false);
        btnGerenciarCursos.setFocusPainted(false);
        btnGerenciarCursos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGerenciarCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGerenciarCursosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGerenciarCursosMouseExited(evt);
            }
        });
        btnGerenciarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarCursosActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnGerenciarCursos);
        btnGerenciarCursos.setBounds(580, 450, 150, 25);

        lblAtendimento.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblAtendimento.setForeground(new java.awt.Color(153, 255, 153));
        lblAtendimento.setText("Atendimento");
        pnlPrincipal.add(lblAtendimento);
        lblAtendimento.setBounds(240, 130, 160, 22);

        lblGerenciaCursos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblGerenciaCursos.setForeground(new java.awt.Color(153, 255, 153));
        lblGerenciaCursos.setText("Cursos");
        pnlPrincipal.add(lblGerenciaCursos);
        lblGerenciaCursos.setBounds(590, 410, 150, 22);

        lblGerenciarPacientes.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblGerenciarPacientes.setForeground(new java.awt.Color(153, 255, 153));
        lblGerenciarPacientes.setText("Gerenciar Pacientes");
        pnlPrincipal.add(lblGerenciarPacientes);
        lblGerenciarPacientes.setBounds(240, 260, 160, 22);

        lblImagemAtendimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ícone Médico P.png"))); // NOI18N
        pnlPrincipal.add(lblImagemAtendimento);
        lblImagemAtendimento.setBounds(130, 130, 280, 100);

        lblImagemPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ícone Enfermeira P.png"))); // NOI18N
        pnlPrincipal.add(lblImagemPacientes);
        lblImagemPacientes.setBounds(130, 260, 280, 130);

        lblImagemGerenciaUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ícone Usuário P Azul.png"))); // NOI18N
        pnlPrincipal.add(lblImagemGerenciaUsuarios);
        lblImagemGerenciaUsuarios.setBounds(470, 260, 270, 130);

        lblCartaoVacina.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblCartaoVacina.setForeground(new java.awt.Color(153, 255, 153));
        lblCartaoVacina.setText("Cartão de Vacinação");
        pnlPrincipal.add(lblCartaoVacina);
        lblCartaoVacina.setBounds(240, 410, 170, 20);

        lblGerenciaUsuarios.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblGerenciaUsuarios.setForeground(new java.awt.Color(153, 255, 153));
        lblGerenciaUsuarios.setText("Gerenciar Usuarios");
        pnlPrincipal.add(lblGerenciaUsuarios);
        lblGerenciaUsuarios.setBounds(580, 260, 170, 22);

        lblRelatorios.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblRelatorios.setForeground(new java.awt.Color(153, 255, 153));
        lblRelatorios.setText("Relatórios");
        pnlPrincipal.add(lblRelatorios);
        lblRelatorios.setBounds(580, 130, 90, 22);

        lblImagemRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ícone Relatório Médico P.png"))); // NOI18N
        pnlPrincipal.add(lblImagemRelatorios);
        lblImagemRelatorios.setBounds(470, 110, 280, 130);

        lblImagemCursos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblImagemCursos.setForeground(new java.awt.Color(255, 255, 255));
        lblImagemCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ícone Relatório P.png"))); // NOI18N
        pnlPrincipal.add(lblImagemCursos);
        lblImagemCursos.setBounds(470, 400, 280, 112);

        lblImagemCartaoVacina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ícone Exames P.png"))); // NOI18N
        lblImagemCartaoVacina.setMaximumSize(new java.awt.Dimension(100, 98));
        lblImagemCartaoVacina.setMinimumSize(new java.awt.Dimension(100, 98));
        pnlPrincipal.add(lblImagemCartaoVacina);
        lblImagemCartaoVacina.setBounds(130, 400, 280, 130);

        lblImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundo principal.png"))); // NOI18N
        pnlPrincipal.add(lblImagemFundo);
        lblImagemFundo.setBounds(0, 0, 874, 620);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarUsuarioMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnAdicionarUsuario);
    }//GEN-LAST:event_btnAdicionarUsuarioMouseEntered

    private void btnAdicionarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarUsuarioMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnAdicionarUsuario);
    }//GEN-LAST:event_btnAdicionarUsuarioMouseExited

    private void btnAdicionarPacienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarPacienteMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnAdicionarPaciente);
    }//GEN-LAST:event_btnAdicionarPacienteMouseEntered

    private void btnAdicionarPacienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarPacienteMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnAdicionarPaciente);
    }//GEN-LAST:event_btnAdicionarPacienteMouseExited

    private void btnEditarCartaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarCartaoMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnEditarCartao);
    }//GEN-LAST:event_btnEditarCartaoMouseEntered

    private void btnEditarCartaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarCartaoMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnEditarCartao);
    }//GEN-LAST:event_btnEditarCartaoMouseExited

    private void btnRelatorioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatorioMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnRelatorio);
    }//GEN-LAST:event_btnRelatorioMouseEntered

    private void btnRelatorioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatorioMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnRelatorio);
    }//GEN-LAST:event_btnRelatorioMouseExited

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        // TODO add your handling code here:
        TelaRelatorios relatorios = new TelaRelatorios();
        relatorios.setVisible(true);
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void btnAlterarPacienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarPacienteMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnAlterarPaciente);
    }//GEN-LAST:event_btnAlterarPacienteMouseEntered

    private void btnAlterarPacienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarPacienteMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnAlterarPaciente);
    }//GEN-LAST:event_btnAlterarPacienteMouseExited

    private void btnAtivarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtivarUsuarioMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnAtivarUsuario);
    }//GEN-LAST:event_btnAtivarUsuarioMouseEntered

    private void btnAtivarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtivarUsuarioMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnAtivarUsuario);
    }//GEN-LAST:event_btnAtivarUsuarioMouseExited

    private void btnAtivarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtivarUsuarioActionPerformed
        // TODO add your handling code here:
        TelaAtivarUsuario alteraRemoveUsuario = new TelaAtivarUsuario();
        alteraRemoveUsuario.setVisible(true);
    }//GEN-LAST:event_btnAtivarUsuarioActionPerformed

    private void btnAdicionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarUsuarioActionPerformed
        // TODO add your handling code here:
        TelaCadastroUsuario cadastroUsuario = new TelaCadastroUsuario();
        cadastroUsuario.setVisible(true);
    }//GEN-LAST:event_btnAdicionarUsuarioActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:       
        int op = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "ATENÇÃO", JOptionPane.YES_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarUsuarioActionPerformed
        // TODO add your handling code here:
        TelaAlteraUsuario alteraUsuario = new TelaAlteraUsuario();
        alteraUsuario.setVisible(true);
    }//GEN-LAST:event_btnAlterarUsuarioActionPerformed

    private void btnAlterarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarUsuarioMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnAlterarUsuario);
    }//GEN-LAST:event_btnAlterarUsuarioMouseEntered

    private void btnAlterarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarUsuarioMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnAlterarUsuario);
    }//GEN-LAST:event_btnAlterarUsuarioMouseExited

    private void btnFichasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFichasMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnFichas);
    }//GEN-LAST:event_btnFichasMouseEntered

    private void btnFichasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFichasMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnFichas);
    }//GEN-LAST:event_btnFichasMouseExited

    private void btnFichasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFichasActionPerformed
        // TODO add your handling code here:
        TelaPrincipal.controlePesquisa = 1;
        PesquisaPaciente pesquisaPaciente = new PesquisaPaciente(this, true);
        pesquisaPaciente.setVisible(true);
    }//GEN-LAST:event_btnFichasActionPerformed

    private void btnAdicionarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarPacienteActionPerformed
        // TODO add your handling code here:
        TelaCadastroPaciente cadastroPacientes = new TelaCadastroPaciente();
        cadastroPacientes.setVisible(true);
    }//GEN-LAST:event_btnAdicionarPacienteActionPerformed

    private void btnGerenciarCursosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGerenciarCursosMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnGerenciarCursos);
    }//GEN-LAST:event_btnGerenciarCursosMouseEntered

    private void btnGerenciarCursosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGerenciarCursosMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnGerenciarCursos);
    }//GEN-LAST:event_btnGerenciarCursosMouseExited

    private void btnGerenciarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarCursosActionPerformed
        // TODO add your handling code here:
        TelaCursos cursos = new TelaCursos();
        cursos.setVisible(true);
    }//GEN-LAST:event_btnGerenciarCursosActionPerformed

    private void btnAlterarPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarPacienteMouseClicked
        // TODO add your handling code here:  
    }//GEN-LAST:event_btnAlterarPacienteMouseClicked

    private void btnAlterarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarPacienteActionPerformed
        // TODO add your handling code here:
        TelaPrincipal.controlePesquisa = 0;
        PesquisaPaciente pesquisa = new PesquisaPaciente(this, true);
        pesquisa.setVisible(true);
    }//GEN-LAST:event_btnAlterarPacienteActionPerformed

    private void btnEditarCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCartaoActionPerformed
        // TODO add your handling code here:
        TelaPrincipal.controlePesquisa = 3;
        PesquisaPaciente pesquisa = new PesquisaPaciente(this, true);
        pesquisa.setVisible(true);
    }//GEN-LAST:event_btnEditarCartaoActionPerformed

    private void btnEncaminhamentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncaminhamentosMouseEntered
        // TODO add your handling code here:
        this.entraMouse(btnEncaminhamentos);
    }//GEN-LAST:event_btnEncaminhamentosMouseEntered

    private void btnEncaminhamentosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncaminhamentosMouseExited
        // TODO add your handling code here:
        this.saiMouse(btnEncaminhamentos);
    }//GEN-LAST:event_btnEncaminhamentosMouseExited

    private void btnEncaminhamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncaminhamentosActionPerformed
        // TODO add your handling code here:
        TelaEncaminhamentos encaminhamentos = new TelaEncaminhamentos();
        encaminhamentos.setVisible(true);
    }//GEN-LAST:event_btnEncaminhamentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarPaciente;
    private javax.swing.JButton btnAdicionarUsuario;
    private javax.swing.JButton btnAlterarPaciente;
    private javax.swing.JButton btnAlterarUsuario;
    private javax.swing.JButton btnAtivarUsuario;
    private javax.swing.JButton btnEditarCartao;
    private javax.swing.JButton btnEncaminhamentos;
    private javax.swing.JButton btnFichas;
    private javax.swing.JButton btnGerenciarCursos;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JLabel lblAtendimento;
    private javax.swing.JLabel lblCartaoVacina;
    private javax.swing.JLabel lblGerenciaCursos;
    private javax.swing.JLabel lblGerenciaUsuarios;
    private javax.swing.JLabel lblGerenciarPacientes;
    private javax.swing.JLabel lblImagemAtendimento;
    private javax.swing.JLabel lblImagemCartaoVacina;
    private javax.swing.JLabel lblImagemCursos;
    private javax.swing.JLabel lblImagemFundo;
    private javax.swing.JLabel lblImagemGerenciaUsuarios;
    private javax.swing.JLabel lblImagemPacientes;
    private javax.swing.JLabel lblImagemRelatorios;
    private javax.swing.JLabel lblRelatorios;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables

}
